[tool.poetry]
name = "js-sdk"
packages = [{ include = "jumpscale" }]

version = "0.1.0"
description = ""
authors = ["xmonader <xmonader@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
js-ng = { git = "https://github.com/threefoldtech/js-ng.git", branch="development" }
python = "^3.6"
pdoc3 = "^0.6.3"
pytest = "^5.0"
codecov = "^2.0"
tox = "^3.13"
pytest-cov = "^2.7"
hypothesis = "^4.28"
pillow = "^6.1"
sonic-client = "^0.0.5"
google-api-python-client = "^1.7"
sendgrid = "^6.0"
minio = "^4.0"
py-trello = "^0.15.0"
pycountry = "^19.8"
python-taiga = "^1.0.0"
dnspython = "^1.16"
PyGithub = "^1.43"
python-digitalocean = "^1.15.0"
twilio = "^6.29"
snakeviz = "^2.0.1"
stellar-sdk = "2.4.1"
pypng = "^0.0.20"
pyqrcode = "^1.2.1"
beaker = "^1.11.0"

[tool.poetry.scripts]
threebot = "jumpscale.entry_points.threebot:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
