name: Build docker image

on:
  push:
    branches: [ master ]
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: docker/build-push-action@v1
          with:
            path: jumpscale/install
            repository: ${{ secrets.DOCKERHUB_USERNAME }}/js-sdk
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            dockerfile: jumpscale/install/Dockerfile
            tags: master
            build_args: BRANCH=master
        - name: Convert Docker image to flist
          run: |
            curl -v -X POST  -H 'Authorization: bearer ${{ secrets.ZEROHUB_TOKEN}}' ${{secrets.ZEROHUB_URL}}/api/flist/me/docker -F 'image=${{ secrets.DOCKERHUB_USERNAME }}/js-sdk:master'
