name: Frontend

on:
  push:
    branches: [ development_frontend_tests ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
     #  - uses: docker://ubuntu:20.04
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - uses: nanasess/setup-chromedriver@master
      - name: Gathering deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git tmux redis restic nginx cron unzip
          sudo service redis stop
          sudo service nginx stop
          poetry run pip3 install pytest selenium

      - name: Install js-sdk
        run: |
          poetry install
      - name: Run tests
        env:
          TNAME: ${{ secrets.TNAME }}
          EMAIL: ${{ secrets.EMAIL }}
          WORDS: ${{ secrets.WORDS }}
        run: |
          threebot start --background
          ps aux
          ss -tlnp
          curl http://localhost
          poetry run pytest -s tests/frontend/tests
