name: Frontend

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - uses: nanasess/setup-chromedriver@master
      - name: Gathering deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git tmux redis restic nginx cron unzip
          sudo service redis stop
          sudo service nginx stop
          poetry run pip3 install pytest selenium pytest-cov

      - name: Install js-sdk
        run: |
          poetry install

      - name: Run tests
        env:
          TNAME: ${{ secrets.TNAME }}
          EMAIL: ${{ secrets.EMAIL }}
          WORDS: ${{ secrets.WORDS }}
        run: |
          sudo setcap CAP_NET_BIND_SERVICE=+eip $(which nginx)
          poetry run pytest -sv tests/frontend/tests --cov=jumpscale --cov-report=xml

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
